Repository trustyai-explainability/llama-stack-provider-lmeval, pull requests merged in 2025-06, with the labels that each got.

#25 feat: Implement namespace resolution in LMEval
  .gitignore
  src/llama_stack_provider_lmeval/lmeval.py
  tests/test_namespace.py
Labels: enhancement

#22 feat: Add GitHub Actions workflow for Trivy security scans
  .github/workflows/security.yml
Labels: enhancement

#26 fix: honour config namespace
  src/llama_stack_provider_lmeval/config.py
  src/llama_stack_provider_lmeval/lmeval.py
  tests/test_namespace.py
Labels: bug

#28 chore: Bump to release 0.1.5
  pyproject.toml
Labels: dependencies

#8 feat: Add demo notebook
  README.md
  demos/00-getting_started_with_lmeval.ipynb
  demos/scripts/deploy_model.sh
  demos/scripts/setup.sh
  scripts/run-server.sh
Labels: enhancement
